server:
  port: 8091
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZeroXD219/miproyecto.git
          searchPaths: config-data
          username: andyllamodiaz@gmail.com
          password: 123Andy123@
          default-label: "main"
  security:
    user:
      name: admin
      password: 12345678 
